GET  http://localhost:5001/register/test


###
POST http://localhost:5001/register
Content-Type: application/json

{
    "email" : "sakthi@gmail.com",
    "password" : "test"
}

###
POST http://localhost:5001/login
Content-Type: application/json

{
    "email" : "sakthivel.r@nextcrack.com",
    "password" : "Test@123"
} 